In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('Datasets.csv')

In [3]:
data.drop(columns=['FN','Active'], inplace=True)

In [4]:
data[data['age'].isna()]

,customer_id,article_id,price,sales_channel_id,sale,product_code,prod_name,product_type_no,product_type_name,product_group_name,...,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc,club_member_status,fashion_news_frequency,age,postal_code
119,584e69e95573097b55f3feb76cf78c2fc6211ffe60e99f...,743840005,0.028797,1,yes,743840,NILS LS CHECK,259,Shirt,Garment Upper body,...,Menswear,55,Contemporary Street,1011,Shirts,"Shirt in soft, checked cotton flannel with a t...",ACTIVE,NONE,NaN,b5d36f844f1f3349ff60e7741c23ea73b828034efa9f51...
247,1d7b486cee7c362095ffb7079ba9c10022c82007d72c16...,852374015,0.033881,2,yes,852374,Berry,265,Dress,Garment Full body,...,Ladieswear,15,Womens Everyday Collection,1013,Dresses Ladies,Calf-length dress in an airy viscose weave. Ro...,ACTIVE,Regularly,NaN,a0b9d341506ce7b3d30c799d6a8e12d427d27c9a54b3c0...
566,f103dda84702e3c2459fb4a9bdb290226d94292dfb9a31...,695542010,0.042356,2,yes,695542,Eden HW paperwaist,272,Trousers,Garment Lower body,...,Ladieswear,15,Womens Everyday Collection,1009,Trousers,"Trousers in woven fabric with a high, pleated ...",ACTIVE,NONE,NaN,7307f90f7d1b7d127657de613b12b9a54cc0498e047df7...
629,23fd26b9a77c0e314c610849f73f9e98bf3666fbdb6abf...,670088001,0.006804,1,No,670088,Flirty Leaf Filigree ab,74,Hair/alice band,Accessories,...,Ladieswear,66,Womens Small accessories,1019,Accessories,Metal Alice band decorated with hole-patterned...,ACTIVE,NONE,NaN,ed5cb3fe92d076c3b942ef8ad230bcd9d77a356ac8e806...
669,330c9c34b6d79e31802be102e360a57c0ae61b15e79128...,699454002,0.014390,2,yes,699454,Wideawake Tie Tanga,59,Swimwear bottom,Swimwear,...,Ladieswear,60,"Womens Swimwear, beachwear",1018,Swimwear,Fully lined bikini bottoms in lace with a low ...,ACTIVE,NONE,NaN,4d05749c09cf4c2347f01d2d8fed11d5b6cd7114133b0f...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1228939,2519db62e046a6acb411606203c3567f9fa0215c6ce552...,783707045,0.003390,1,yes,783707,1pk Fun,302,Socks,Socks & Tights,...,Menswear,26,Men Underwear,1021,Socks and Tights,"Socks in a soft, jacquard-knit cotton blend wi...",ACTIVE,NONE,NaN,3266dcb8b3674d902223f853d3f97cc93f089c984f22b3...
1229055,7ae354a1ec2a4c0c32ad2fed2871d45030afc6a96e7cef...,696594003,0.004102,1,yes,696594,ANGELICA S.0,259,Shirt,Garment Upper body,...,Divided,53,Divided Collection,1010,Blouses,Sleeveless blouse in an airy viscose weave wit...,ACTIVE,NONE,NaN,a5773836d9e96e1f76f8f6f83f2039dbfb26dbe45e37a8...
1229140,057ae19623c5be65910d067232b4353eb40d0827fdf523...,759425001,0.084729,2,yes,759425,Appletini,265,Dress,Garment Full body,...,Ladieswear,11,Womens Tailoring,1013,Dresses Ladies,Long dress in a pleated weave. Narrow cut with...,PRE-CREATE,NONE,NaN,66d6ee7f9a44bf530bbd0097091d37cf35cca366832204...
1229388,631c23a62fe5022835b81d0c233e28c04f0ed463f4b08c...,615021001,0.002695,1,yes,615021,Luisa tee,255,T-shirt,Garment Upper body,...,Ladieswear,15,Womens Everyday Collection,1005,Jersey Fancy,T-shirt in jersey with a motif.,ACTIVE,Regularly,NaN,c33fcaca5cb9d12cccc61a14f65dff06ff37d18ed58814...
1229789,31ec2ec937bee744c4f76b704e5b93be9ecd64c3e0953c...,758650002,0.033881,2,yes,758650,RICHIE SKIRT S.0,275,Skirt,Garment Lower body,...,Divided,53,Divided Collection,1012,Skirts,"Short, pleated skirt in woven fabric with a co...",PRE-CREATE,NONE,NaN,c55f9b6e3aeb9be6ff9d16cfe5f28fba75c3806ea61170...

In [5]:
data['age'].fillna(data['age'].median(), inplace=True)

In [6]:
data[data['age'].isna()]

Empty DataFrame
Columns: [customer_id, article_id, price, sales_channel_id, sale, product_code, prod_name, product_type_no, product_type_name, product_group_name, graphical_appearance_no, graphical_appearance_name, colour_group_code, colour_group_name, perceived_colour_value_id, perceived_colour_value_name, perceived_colour_master_id, perceived_colour_master_name, department_no, department_name, index_code, index_name, index_group_no, index_group_name, section_no, section_name, garment_group_no, garment_group_name, detail_desc, club_member_status, fashion_news_frequency, age, postal_code]
Index: []

[0 rows x 33 columns]

In [7]:
data[data['club_member_status'].isna()]

,customer_id,article_id,price,sales_channel_id,sale,product_code,prod_name,product_type_no,product_type_name,product_group_name,...,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc,club_member_status,fashion_news_frequency,age,postal_code
38,0733850094333610c88db99e561ddb934a6fe1d97ddb26...,771338003,0.021678,2,yes,771338,Denize cord,275,Skirt,Garment Lower body,...,Ladieswear,15,Womens Everyday Collection,1012,Skirts,Short A-line skirt in wide-wale cotton corduro...,NaN,NONE,27.0,45a5fef22bfe6eb9b93fbb29655f8403902290335a5590...
471,3fcd2398a6cbf5a54870cbbe1cbc6d87018782e038603e...,856440001,0.042356,2,yes,856440,Cava Shirt dress,265,Dress,Garment Full body,...,Divided,53,Divided Collection,1013,Dresses Ladies,Short dress in a softly draping weave with a c...,NaN,NONE,62.0,efa295cab070e148b86021159c1ba24939291c0b541e9c...
942,1e5c2901fe4677a84c5ca76de678df6da97e00fbd7605a...,355569002,0.008458,1,yes,355569,Nicky Long,253,Vest top,Garment Upper body,...,Divided,51,Divided Basics,1002,Jersey Basic,"Long, fitted jersey top with narrow adjustable...",NaN,NONE,28.0,15b0f5a373ca2515e5548265a49b2706abe7f546aeec98...
947,a8ea1fe4d26bb2501ebf375b7770d3d8f1f60a444eb454...,624486050,0.008458,2,yes,624486,Brit Baby Tee,255,T-shirt,Garment Upper body,...,Divided,51,Divided Basics,1002,Jersey Basic,"Short, fitted top in ribbed cotton jersey with...",NaN,NONE,16.0,2c09d8e88b89a296b7865ed81fae1a1e3b99359fe46c1b...
1202,aa7cc9db7f63b8d547fb4703d5f26a4ff5a99b8da36ecf...,863002001,0.035576,2,yes,863002,Higgings,245,Cardigan,Garment Upper body,...,Ladieswear,15,Womens Everyday Collection,1003,Knitwear,"Cardigan in a soft, fluffy knit with a V-neck,...",NaN,NONE,36.0,861a540d29c74702ea350138a907d1d3f687e6005874ac...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1227249,9bc2eb9f1434d8704b809a44e4159fe3400b027741e666...,662879004,0.025407,2,yes,662879,BB Cape Own fancy,78,Other accessories,Accessories,...,Baby/Children,43,"Kids Accessories, Swimwear & D",1019,Accessories,Fancy dress cape in jersey with a concealed ho...,NaN,NONE,41.0,23617c4fa3c7aba109782abd33fb6255a95e3d83160993...
1227690,b5838e5006f5b982927355a74ed5a430c19dbb0d38c5ff...,720106001,0.047441,2,yes,720106,PALM SHAWL COLLAR CARDIGAN,245,Cardigan,Garment Upper body,...,Menswear,20,Contemporary Smart,1003,Knitwear,Cardigan knitted in a soft cotton blend with a...,NaN,NONE,58.0,fe814f9d1b8a657f20a30666c230cba0ad41a3172d5a6d...
1227741,59f217064d09393b51899e6db7bfa78149133b30516bba...,537688013,0.050831,2,yes,537688,Rachel,252,Sweater,Garment Upper body,...,Ladieswear,15,Womens Everyday Collection,1003,Knitwear,Long polo-neck jumper in a soft knit with long...,NaN,NONE,24.0,6dc4590a347d9d9ae76eb33c02a19b17368db75adbeac6...
1228603,e8bdd5514aaee821186246b41b41d005f9bb2453bc5f72...,578474007,0.067780,2,yes,578474,Dayzy,264,Blazer,Garment Upper body,...,Ladieswear,11,Womens Tailoring,1008,Dressed,Gently fitted jacket in woven fabric with welt...,NaN,NONE,86.0,16794f131214279e0a5666158958c93a8d33e5af6f9a67...
1229211,8ea2eb98541c87c23eeeec2df34e9b81b43767d9159d5d...,733097008,0.008458,2,yes,733097,Saga body,256,Bodysuit,Garment Upper body,...,Ladieswear,15,Womens Everyday Collection,1005,Jersey Fancy,"Sleeveless, turtleneck body in stretch, ribbed...",NaN,NONE,30.0,768c3c4cad9a55b382a65fd303a5daff7f2e59c60895b1...

In [8]:
data['club_member_status'].fillna('ACTIVE', inplace=True)

In [9]:
data[data['club_member_status'].isna()]

Empty DataFrame
Columns: [customer_id, article_id, price, sales_channel_id, sale, product_code, prod_name, product_type_no, product_type_name, product_group_name, graphical_appearance_no, graphical_appearance_name, colour_group_code, colour_group_name, perceived_colour_value_id, perceived_colour_value_name, perceived_colour_master_id, perceived_colour_master_name, department_no, department_name, index_code, index_name, index_group_no, index_group_name, section_no, section_name, garment_group_no, garment_group_name, detail_desc, club_member_status, fashion_news_frequency, age, postal_code]
Index: []

[0 rows x 33 columns]

In [10]:
data[data['fashion_news_frequency'].isna()]

,customer_id,article_id,price,sales_channel_id,sale,product_code,prod_name,product_type_no,product_type_name,product_group_name,...,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc,club_member_status,fashion_news_frequency,age,postal_code
323,4a879c9c97a74670b1b9ecba9552dfec68ce7533073b19...,611221009,0.016492,1,yes,611221,Bernie,254,Top,Garment Upper body,...,Ladieswear,15,Womens Everyday Collection,1005,Jersey Fancy,Top in soft cotton jersey with a yoke and shor...,ACTIVE,NaN,41.0,165b96e84467d894f15b85e07766e2ad6c2bb820450614...
648,18430239dacca65d6b559aeff040cebb8b2e12efa23c1f...,331093001,0.025407,2,yes,331093,LEA jumpsuit,265,Dress,Garment Full body,...,Divided,51,Divided Basics,1002,Jersey Basic,Sleeveless jersey jumpsuit with a deep necklin...,ACTIVE,NaN,44.0,162776af3a4156aeac21fbe20be2ca918731e7ab6efd03...
905,4eb81532d5b170abc387658f907621f6bef0d9f83b6be4...,879248005,0.016932,1,yes,879248,Glamping,274,Shorts,Garment Lower body,...,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Short shorts in lightweight sweatshirt fabric ...,ACTIVE,NaN,24.0,457319fa44f52130da0ebb4c3effe70ae9dea0af3e4663...
948,5d7a904380a54c61e3ad7a18e8cea0005ce312171a51d9...,756662001,0.012186,1,yes,756662,Malou Head Band,74,Hair/alice band,Accessories,...,Ladieswear,65,Womens Big accessories,1019,Accessories,Headband in a soft rib knit with a decorative ...,ACTIVE,NaN,43.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...
988,2bf70f1ae85f8677c60c297e6b6b4bf0a2362639fb5588...,278811002,0.033881,2,yes,278811,Hilly Biker 2pk LT,286,Underwear bottom,Underwear,...,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear",Shaping bikers in microfibre with a high waist...,ACTIVE,NaN,40.0,407b524c24d583db7c730c0c867e6fb34f1f2c3ab23116...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1229437,f10ae38e4834231ffe1fcedbd8d89c8a5fdea7b182cf0d...,573716054,0.022864,1,yes,573716,Kanta slacks RW,272,Trousers,Garment Lower body,...,Ladieswear,15,Womens Everyday Collection,1009,Trousers,Ankle-length cigarette trousers in a stretch w...,ACTIVE,NaN,55.0,a671c4d610c78ebee9422283ffcb9b09bf5437372bbcd1...
1229481,928e0778b0eb66df1099a89ff0f5eaa4b71b23c6cb57d5...,535035001,0.118627,2,yes,535035,Ultimate parka,262,Jacket,Garment Upper body,...,Divided,58,Divided Selected,1007,Outdoor,Padded parka with a pile-lined hood with a tab...,ACTIVE,NaN,48.0,4e29c113441db198c36085c5a79748cb6ba93b9aca24e6...
1229495,2c9f6536fe8cf8f702abaf6b70a7c9d335bf7b84168dc1...,748025002,0.033881,2,yes,748025,B Sibylla Kaftan,300,Sarong,Swimwear,...,Ladieswear,60,"Womens Swimwear, beachwear",1018,Swimwear,Kaftan in an airy weave with buttons down the ...,ACTIVE,NaN,53.0,ede0645f67633501110dd31908cc8c7d6b7f7b77e5dca7...
1229522,d8f42cbc938cee56f5ffd98b756810be3d36c9c0a42080...,563453001,0.010036,2,No,563453,Prince softbra V.5,306,Bra,Underwear,...,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Soft, non-wired lace bra that gives the bust a...",PRE-CREATE,NaN,52.0,4bb64b360f87b9c0d5dff3294389a28ab361d492e4b2f0...
1229825,6306cb2c62532aca4de5f457a3f93f0616768871456507...,653188027,0.010308,1,No,653188,Sigge sneaker sock 5p.,302,Socks,Socks & Tights,...,Divided,51,Divided Basics,1017,"Under-, Nightwear",Shaftless socks in a fine-knit cotton blend wi...,ACTIVE,NaN,43.0,e3bfe7bdff73c37b3b819448645936452b903970487ce6...

In [11]:
data['fashion_news_frequency'].fillna(method ='ffill', inplace=True)

In [12]:
data[data['fashion_news_frequency'].isna()]

Empty DataFrame
Columns: [customer_id, article_id, price, sales_channel_id, sale, product_code, prod_name, product_type_no, product_type_name, product_group_name, graphical_appearance_no, graphical_appearance_name, colour_group_code, colour_group_name, perceived_colour_value_id, perceived_colour_value_name, perceived_colour_master_id, perceived_colour_master_name, department_no, department_name, index_code, index_name, index_group_no, index_group_name, section_no, section_name, garment_group_no, garment_group_name, detail_desc, club_member_status, fashion_news_frequency, age, postal_code]
Index: []

[0 rows x 33 columns]

In [13]:
data[data['detail_desc'].isna()]

,customer_id,article_id,price,sales_channel_id,sale,product_code,prod_name,product_type_no,product_type_name,product_group_name,...,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc,club_member_status,fashion_news_frequency,age,postal_code
118,cecf1ab4992ac483c6ffb12a9fab114238df46d64e68e8...,578311015,0.025407,2,yes,578311,KATE PQ ballerina,86,Ballerinas,Shoes,...,Ladieswear,64,Womens Shoes,1020,Shoes,NaN,ACTIVE,NONE,36.0,495dc48e7dcbaef0f49649dc8c3b9b3848297f5085c130...
384,8d0fad12917d75fdf78230f97dd1c451d2e93517c0410b...,661147008,0.050831,1,yes,661147,SPEED Ace,252,Sweater,Garment Upper body,...,Ladieswear,11,Womens Tailoring,1003,Knitwear,NaN,ACTIVE,NONE,52.0,0cfed4081f88cfbaffe0da34460c1b9e0c03e0f8e645a5...
431,468f9f68937de6cee3ebc6f645c634b45acb2007193e72...,742916001,0.008458,2,yes,742916,C Antibes Tie Tanga,59,Swimwear bottom,Swimwear,...,Ladieswear,60,"Womens Swimwear, beachwear",1018,Swimwear,NaN,ACTIVE,Regularly,49.0,c81eef54303b4a1da71898fc974b0d3790efcf40d94bd9...
481,2e79c17b3d12ad4d01aebca09474ca05b816ef47e06485...,693500002,0.022017,2,yes,693500,Margarita highwaist hipster,286,Underwear bottom,Underwear,...,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear",NaN,ACTIVE,Regularly,25.0,b5dfe7963bb548c8d64eb9a55ca592f64768e1d32eff6f...
572,4bff56ab43dbe8a6a98374cdd39c11020d7de7285d4873...,567993016,0.020322,2,yes,567993,IZZY loose tee (1),255,T-shirt,Garment Upper body,...,Sport,5,Ladies H&M Sport,1005,Jersey Fancy,NaN,ACTIVE,NONE,36.0,6726e1200c48dfaeb8fd1c7c58fa0a087995dd6c78928a...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1228721,2120ad8b18f24ed0ed6f153d1c769d43d13264019e5f70...,567993042,0.013542,1,yes,567993,IZZY loose tee (1),255,T-shirt,Garment Upper body,...,Sport,5,Ladies H&M Sport,1005,Jersey Fancy,NaN,ACTIVE,NONE,31.0,067fd4f5b8e614f68c1b1fb9cc7d2a4aa528799c048c97...
1228820,7269a98b4fe8b7bf766bb50de3beaf48cca1af5c3e2738...,469039019,0.022017,2,yes,469039,Henrik ballerina,86,Ballerinas,Shoes,...,Ladieswear,64,Womens Shoes,1020,Shoes,NaN,ACTIVE,Regularly,42.0,c1b036d30576c994cfc647d0aeaa65d63367508c6d1971...
1228856,b5231106586346a3ab63ffeab2b47d9ee8a75fb312ece8...,686631001,0.009305,1,yes,686631,Maggie RW tapered,272,Trousers,Garment Lower body,...,Ladieswear,15,Womens Everyday Collection,1009,Trousers,NaN,ACTIVE,NONE,21.0,7e0f3fed7c0435d0148acc64286b474157f2af8566abcf...
1228892,fd68f3d70e91d7d676fb81b1c60510bf3248924987416a...,620081001,0.025407,2,yes,620081,Tulip jumper,252,Sweater,Garment Upper body,...,Ladieswear,15,Womens Everyday Collection,1005,Jersey Fancy,NaN,ACTIVE,NONE,50.0,850b504952e512bc5928f0ab9331884ffbefb8091730d1...
1229756,179e7b1aa0c5b3339d280c0cc7ba3d383a12e4cf824161...,693748001,0.050831,2,yes,693748,ED Aladin,252,Sweater,Garment Upper body,...,Ladieswear,2,H&M+,1003,Knitwear,NaN,ACTIVE,NONE,38.0,031e6d1b4dee1495a415aca057263b7d30a19f04834428...

In [14]:
data['detail_desc'].fillna(method ='ffill', inplace=True)

In [15]:
data[data['detail_desc'].isna()]

Empty DataFrame
Columns: [customer_id, article_id, price, sales_channel_id, sale, product_code, prod_name, product_type_no, product_type_name, product_group_name, graphical_appearance_no, graphical_appearance_name, colour_group_code, colour_group_name, perceived_colour_value_id, perceived_colour_value_name, perceived_colour_master_id, perceived_colour_master_name, department_no, department_name, index_code, index_name, index_group_no, index_group_name, section_no, section_name, garment_group_no, garment_group_name, detail_desc, club_member_status, fashion_news_frequency, age, postal_code]
Index: []

[0 rows x 33 columns]

In [16]:
data.sale

0          yes
1          yes
2          yes
3          yes
4          yes
          ...
1229995    yes
1229996    yes
1229997    yes
1229998    yes
1229999    yes
Name: sale, Length: 1230000, dtype: object

In [17]:
data['sale'].replace(['No', 'yes'],
                        [0, 1], inplace=True)

In [18]:
data[data['sale']==0]

,customer_id,article_id,price,sales_channel_id,sale,product_code,prod_name,product_type_no,product_type_name,product_group_name,...,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc,club_member_status,fashion_news_frequency,age,postal_code
18,4cdfb097c28c1e74f45fd8bf92e735b73da3f5d1371431...,717477012,0.011057,2,0,717477,Rita Ringer Tee.,255,T-shirt,Garment Upper body,...,Divided,51,Divided Basics,1002,Jersey Basic,T-shirt in soft jersey with a contrasting colo...,ACTIVE,NONE,19.0,642d0294d47dee89baf202ee1542fab8f2765ad24b4f99...
50,1f98c09accbb115e84af724448b537f1daa28657d14ce8...,294895015,0.002712,1,0,294895,Rodney basic beanie,75,Hat/beanie,Accessories,...,Divided,52,Divided Accessories,1019,Accessories,"Double-layered hat in a soft, fine knit with a...",ACTIVE,NONE,22.0,f37ade7041ef02d74258e383674e8321e1310dadfa6735...
144,4f21801f964fa59def0f5833a0be32c1c32baf0343423a...,633464001,0.090015,1,0,633464,Cake dress,265,Dress,Garment Full body,...,Ladieswear,14,Womens Premium,1013,Dresses Ladies,Calf-length dress in woven fabric with embroid...,ACTIVE,Regularly,33.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...
187,e2fd3c6d6c992566be9d5618da8c7eceb7f4541ecf252a...,783325001,0.063143,1,0,783325,Frank PQ slider,91,Sandals,Shoes,...,Menswear,27,Men Shoes,1020,Shoes,Pool shoes with a wide strap and moulded insol...,ACTIVE,NONE,54.0,fd50474757d1767f1d12a2dcdad863c9911018c98cecbd...
189,5768fe9388e3fbbfdaac16aa50afc97f1c175cb0c29d16...,857232001,0.012455,2,0,857232,Sunglasses Ibbe,81,Sunglasses,Accessories,...,Menswear,25,Men Accessories,1019,Accessories,Geometric-shaped sunglasses with thin frames a...,PRE-CREATE,NONE,49.0,d98ce11631f4326fd439e53b0d10dac4843434de29b29f...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1229926,f578f6b04bce7871cf358f5c2eafb387397763053b0348...,903096001,0.040997,1,0,903096,Bixa terry dress,265,Dress,Garment Full body,...,Ladieswear,6,Womens Casual,1005,Jersey Fancy,"Short, wide dress in soft sweatshirt fabric ma...",ACTIVE,Regularly,30.0,74198e04274b93d4f5985b0d651c690c1bc4d40a5dd097...
1229955,c0b7fa0477e8467d7140cd78dd9863927df67a84fb8e8a...,810792007,0.033881,2,0,810792,Jacob trs,272,Trousers,Garment Lower body,...,Sport,49,Kids Sports,1001,Unknown,Sports trousers in sturdy jersey with a drawst...,ACTIVE,NONE,34.0,77f62411566276ff1420de05b461017229b19e534944a9...
1229970,9a07e8b5e5421ba1b4fdebeb06bb76a08177e24aed8c8a...,579169002,0.024138,1,0,579169,Silver Lake shirt,259,Shirt,Garment Upper body,...,Baby/Children,47,Young Boy,1011,Shirts,Shirt in washed cotton twill with appliqués an...,ACTIVE,NONE,37.0,cd5ad0cd6e2813ebedd66efe0d972de4cdcd822f927d44...
1229973,57a75d928d9ecd7b110733c5727e706864f0f99f30ff21...,680355003,0.007500,2,0,680355,EBBA CHINILLE SCARF,80,Scarf,Accessories,...,Divided,52,Divided Accessories,1019,Accessories,Scarf knitted in soft chenille with faux fur p...,ACTIVE,Regularly,29.0,08ae7b0e2eebb2c1f441362c41e15999f733216edf8a13...
1229986,2855bc15a80c32b71133d4181b40feac2dac749693f78a...,850288001,0.012525,2,0,850288,Mallorca fancy RIB top,254,Top,Garment Upper body,...,Baby/Children,76,Kids Girl,1005,Jersey Fancy,Patterned top in crinkled jersey. Flutter slee...,PRE-CREATE,NONE,53.0,c3fa14376b0995e11dd8c49c5d6084dc4d193f8c6d12a8...

In [19]:
data = data.drop_duplicates(keep='first')

In [23]:
data.duplicated().sum()

0

In [20]:
data.to_csv('Dataset_cleaned.csv', index=False)

In [21]:
#from pandas_profiling import ProfileReport

#profile = ProfileReport(data, title = "Clean Datasets")
#profile.to_file(output_file = 'output_Clean.html')